### ISSUE TITLE
Cannot reconnect to machine after a reboot

### ISSUE THREAD

**Issue by leehambley** [Fred78290/vagrant-multipass#2]
Just was hit by this today, I have rebooted without doing a `vagrant halt` and when rebooting the multipass image was still up `mycompany-dev` (I presume multipass restarts containers on boot, I need to look into this).  

When trying to stop the image via multipass to restart it with `vagrant up` worked almost worked OK the machine came up, but vagrant got stuck at `default: Waiting for SSH...`:

```
vagrant up
Bringing machine 'default' up with 'multipass' provider...
==> default: VM already created.
==> default: Powering on VM...
==> default: Waiting for SSH...
^C==> default: Waiting for cleanup before exiting...
Vagrant exited after cleanup due to external interrupt.
```

I could enter the console with multipass which I _guess_ is a serialconsole or some SSH magic, either way `vagrant ssh` unfortunately didn't work as it the machine didn't have my SSH key.

Can I just ask, although this plugin is WIP is it expected that the machine has to be recreated every reboot, or is my system exceptionally broken (M1 mac, using qemu backend)

**Comment by leehambley** [comment]
This might be a mistake on my part, I overlooked that my colleague moved a line:

``` ruby
  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "192.168.56.5", name: "vboxnet0"
```

into a virtualbox specific provider block, so I _guess_ my VM was leftover with an unusual IP address and vagrant couldn't find it. After a staged reboot for testing just now, mv vagrant machine was already up and accessible with `ssh default` (I had previously put my `vagrant ssh-config > ~/.ssh/config`) and from the directory with the `Vagrantfile` `vagrant ssh` works too.

**Comment by Fred78290** [comment]
:)
config.XX.YYY is global setting, if you don't specify the default provider it will be virtualbox. So multipass doesn't allow specify IP at launch, except with LXD or KVM driver on linux with a cloud-init file.

If your vagrant file must support different provider, you must use subconfig by provider such as

```
	config.vm.provider 'multipass' do |multipass, subconfig|
		subconfig.vm.box = "multipass"
                subconfig.vm.network = ....
	end
````

Regards

**Comment by leehambley** [comment]
Thanks, indeed, I know that the `vm.network` line was misplaced, now indeed it's in a virtualbox specific block, I think this might explain why I "lost" the ability for Vagrant to connect to my VM.
