### ISSUE TITLE
Vagrant plus Multipass as the solution to the M1 Mac Vagrant Problem

### ISSUE THREAD

**Issue by godber** [Fred78290/vagrant-multipass#5]
I haven't had an opportunity to try this project yet, since I just found it this morning.  But I think there could be rapidly increasing demand for the functionality this project provides.  As M1 macs roll out and the Intel models disappear people are going to realize their options for linux virtualization on M1 is in a bad state.  I think multipass has a good chance of being a key building block for future virtualization based workloads on M1 (I'm ignoring vmware and parallels deliberately, considering only open source community driven things).

I guess my question here is, since this project is a little older, has anyone had success using this on modern late 2022 versions of vagrant and multipass ... and specifically on Apple M1 architectures?

**Comment by Fred78290** [comment]
> I haven't had an opportunity to try this project yet, since I just found it this morning.  But I think there could be rapidly increasing demand for the functionality this project provides.  As M1 macs roll out and the Intel models disappear people are going to realize their options for linux virtualization on M1 is in a bad state.  I think multipass has a good chance of being a key building block for future virtualization based workloads on M1 (I'm ignoring vmware and parallels deliberately, considering only open source community driven things).
> 
> 
> 
> I guess my question here is, since this project is a little older, has anyone had success using this on modern late 2022 versions of vagrant and multipass ... and specifically on Apple M1 architectures?

Not yet but I think with memory limitations the Mac left the world of the virtualization.

My project at the begin was necessary because I was owner of a MacPro with 128Go Ram and 4To of Hd and with my job I needed to build proto with vagrant before migrating to VMware infrastructure not owned by me 😂

**Comment by godber** [comment]
Thanks for the response @Fred78290.

>memory limitations the Mac left the world of the virtualization.

What limitations are you concerned with?

**Comment by Fred78290** [comment]
> Thanks for the response @Fred78290.
> 
> 
> 
> >memory limitations the Mac left the world of the virtualization.
> 
> 
> 
> What limitations are you concerned with?
> 
> 

On mac mini with 16go of ram with a system eating 6go how you can build a VM cluster with vagrant. sure U can still to up a single VM  but the vagrant interesting is out of play.

If you need to prototype a small cluster, now on Mac is not able without to spend USD and buy a macbook pro with 16go.
apple left the target of real developers like me (35 years on the plateform, former NeXT developer)

Apple choose to build jewelry not computer.

Well also after 35 years of apple usage for me apple look like a soviet.
Now i choose the freedom and linux.

**Comment by godber** [comment]
Aha, ok.  Thanks for the reply.
